services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: dev.env
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_HOST=${DJANGO_DB_HOST}
      - POSTGRES_PORT=${DJANGO_DB_PORT}
    restart: always
    networks:
      - volunteer

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8053
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    env_file:
      - dev.env
    ports:
      - 8053:8053
    depends_on:
      - db
    networks:
      - volunteer

  bot:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: python run_bot.py
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web
    env_file:
      - dev.env
    networks:
      - volunteer

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - volunteer
 
volumes:
  postgres_data:
  static_volume: 

networks:
  volunteer: