services:
  db:
    image: postgres:16-buster
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8053
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - static_volume:/home/app/web/static
      - ./media:/home/app/web/media
    env_file:
      - .env
    ports:
      - 8053:8053
    depends_on:
      - db

  bot:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: python run_bot.py
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    restart: always
 
volumes:
  postgres_data:
  static_volume: 