services:
  db:
    container_name: volunteer-postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_HOST=${DJANGO_DB_HOST}
      - POSTGRES_PORT=${DJANGO_DB_PORT}
    restart: always
    networks:
      - volunteer

  web:
    container_name: volunteer-admin
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8053
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    env_file:
      - .env
    ports:
      - 8053:8053
    depends_on:
      - db
    networks:
      - volunteer

  bot:
    container_name: volunteer-bot
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: python run_bot.py
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    networks:
      - volunteer

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - volunteer
    volumes:
      - redis-data:/data
 
volumes:
  postgres_data:
  static_volume: 
  redis-data:

networks:
  volunteer: